"""
Analytics Query Plan Contract & Pydantic Data Models.
Enforces strict schema validation, operator allowlists, and semantic constraints.
"""

from typing import List, Optional, Any, Literal
# pyrefly: ignore [missing-import]
from pydantic import BaseModel, Field, field_validator


ALLOWED_OPERATORS = {"=", "!=", ">", ">=", "<", "<=", "IN", "BETWEEN", "LIKE"}
ALLOWED_AGGREGATIONS = {"sum", "count", "avg", "min", "max"}
ALLOWED_TABLES = {
    "analytics_orders",
    "analytics_order_items",
    "analytics_products",
    "analytics_customers",
    "analytics_salespersons",
    "analytics_payments",
    "analytics_due_assignments",
}
ALLOWED_ENTITIES = {
    "orders",
    "payments",
    "customers",
    "salespersons",
    "products",
    "due_assignments",
    "derived_due",
}


class FilterCondition(BaseModel):
    field: str
    operator: str = "="
    value: Any

    @field_validator("operator")
    @classmethod
    def validate_operator(cls, v: str) -> str:
        clean_op = v.strip().upper()
        if clean_op not in ALLOWED_OPERATORS:
            raise ValueError(f"Operator '{v}' not allowed. Must be one of: {sorted(ALLOWED_OPERATORS)}")
        return clean_op


class MetricSpec(BaseModel):
    field: str
    aggregation: str = "sum"

    @field_validator("aggregation")
    @classmethod
    def validate_aggregation(cls, v: str) -> str:
        clean_agg = v.strip().lower()
        if clean_agg not in ALLOWED_AGGREGATIONS:
            raise ValueError(f"Aggregation '{v}' not allowed. Must be one of: {sorted(ALLOWED_AGGREGATIONS)}")
        return clean_agg


class DateFilter(BaseModel):
    type: Literal[
        "today",
        "yesterday",
        "last_7_days",
        "this_month",
        "last_month",
        "lifetime",
        "all_time",
        "custom",
    ]
    start_date: Optional[str] = None
    end_date: Optional[str] = None


class SortSpec(BaseModel):
    field: str
    direction: Literal["asc", "desc"] = "desc"


class AnalyticsQueryPlan(BaseModel):
    """
    Structured query plan representation generated by LLM.
    Strictly isolated from direct SQL generation.
    """
    intent: str
    entity: Optional[str] = None
    metrics: List[MetricSpec] = Field(default_factory=list)
    dimensions: List[str] = Field(default_factory=list)
    filters: List[FilterCondition] = Field(default_factory=list)
    date_filter: Optional[DateFilter] = None
    sort: Optional[SortSpec] = None
    limit: Optional[int] = None

    # Clarification / Guard handling
    needs_clarification: bool = False
    clarification_options: List[str] = Field(default_factory=list)
    clarification_message: Optional[str] = None

    # Security rejection handling
    is_security_rejection: bool = False
    rejection_reason: Optional[str] = None
